### PR TITLE
[FWK-366] disable logging for tests

### PR DESCRIPTION
**Pull request by aprakash-gc**

### CODE REVIEW

**Comment by siennamw** [comment]
👍

**Comment by aprakash-gc** [comment]
> This seems slightly hacky to me, but I'm seeing it recommended by the owner of the bunyan repo ([trentm/node-bunyan#148 (comment)](https://github.com/trentm/node-bunyan/pull/148#issuecomment-63018668)), so I guess it's the sanctioned solution!

Agreed, it's the best I could find as well though

**Comment by bearfact** [comment]
+1

**Comment by bearfact** [comment]
@aprakash-gc @siennamw now that I see this would it not make more sense to set the LOG_LEVEL to fatal in test environments and not have this special flag?

**Comment by siennamw** [comment]
@bearfact Fair point.  It seems a bit silly to use one .env variable to override another.

**Comment by aprakash-gc** [comment]
depends on if we'd ever use `FATAL` logging otherwise and would also want to prevent that from showing up in tests

**Comment by bearfact** [comment]
> depends on if we'd ever use `FATAL` logging otherwise and would also want to prevent that from showing up in tests

I think if we had a FATAL error it would apply to any instance the app is running, test, prod, etc.  I'm going to suggest we use FATAL and not add a custom implementation.

**Pull request closed without merging**
