### PR TITLE
[FWB-79] Sanitize middleware to strip non-ascii and dangerous HTML

### PR DESCRIPTION
**Pull request by siennamw**
https://greenchef.atlassian.net/browse/FWB-79

For use in both shipping-platform and core API when available.

Core API (script to strip non-ascii from some user fields): https://github.com/greenchef/greenchef/pull/5139

### CODE REVIEW

**Comment by SealedSaint** [comment]
@siennamw Now that I'm looking at this, I'm wondering if we wouldn't want it as a policy in the gateway. Let's discuss.

**Comment by josh-philpott** [comment]
👍

**Comment by siennamw** [comment]
@SealedSaint Yes, let's discuss.  Sorry, just have been busy with other things.

**Comment by siennamw** [comment]
Moving to the gateway level instead.  Closing this PR

**Pull request closed without merging**
