### PR TITLE
Fixes reliance on strict query by deleting params from req/body/query…

### PR DESCRIPTION
**Pull request by tom-con**
… when stripping off search options

### CODE REVIEW

**Comment by bearfact** [comment]
@tom-con bump the package version

**Comment by Brady-Conn** [comment]
👍

**Comment by bearfact** [comment]
👍

**Comment by bearfact** [comment]
@tom-con rebase this and make sure we have the correct version number, then I'll close this.

**Comment by tom-con** [comment]
> @tom-con rebase this and make sure we have the correct version number, then I'll close this.

done @bearfact

**Comment by bearfact** [comment]
👍

**Pull request merged**
